name: Tidelift Scanner Example
on:
  issues:
    types: [opened, edited]
    
jobs:
  tidelift_scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: macowie/issue_scanner_test@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tidelift-token: ${{ secrets.TIDELIFT_TOKEN }}
    permissions: write-all
      # issues: write
      # pull-requests: write
